### ISSUE TITLE
Empty response from analyze_sentiment using Dutch language

### ISSUE THREAD

**Issue by GiorgioJ** [googleapis/python-language#23] opened 2020-06-05 09:06 UTC
I am playing around with the Python SDK and think I've found a bug. Please review the following and let me know if you need any other details. 

#### Environment details

- Python 3.6.2 running Mac OS
- Using google.cloud.language_v1

#### Steps to reproduce

1. Send a Document to LanguageServiceClient -> analyze_sentiment
2. Include a Dutch string
3. Expect the response to be empty. The language is detected correctly, but no sentiment has been detected

#### Code example

```python
document = language.types.Document(
                    content= "Dit is een nederlandse string. Vandaag is een super mooie dag.",
                    type=enums.Document.Type.PLAIN_TEXT
                    )
              
                sentiment = client.analyze_sentiment(document=document)
                
                print(sentiment)
```

#### Output
```
document_sentiment {
}
language: "nl"
```

Passing a ``` langauge=nl ``` parameter doesn't resolve the issue. I've tried other languages an that seems to work fine.

**Comment by emma-c-dev** [comment] 2021-02-19 09:43
@plamut Hi! I was wondering if there is any news about this issue? I am getting the exact same empty response as @GiorgioJ. Please let me know if I can provide additional information!

**Comment by plamut** [comment] 2021-02-19 11:44
@emma-c-dev Hi Emma, I cannot really say much, unfortunately, because I'm not a maintainer of this library, I merely transitioned the issue to the correct repository back then.

@busunkim96 As one of the more recent human committers, do you know whom to ping to have a look?

**Comment by emma-c-dev** [comment] 2021-02-19 14:11
Thank you @plamut for passing this issue on!

To add some information to my previous comment, my code worked correctly with language 'en' and English input text, I used the library language `from google.cloud import language` and some results pasted below.

`sentence="wat een geweldige film. alles was voortreffelijk en de acteurs waren geweldig."`
`document = types.Document(content=sentence,type=enums.Document.Type.PLAIN_TEXT)`
`annotations = client.analyze_sentiment(document=document)`
`print(annotations)`
`document_sentiment {
}
language: "nl"`

`sentence="what a wonderful movie. everything was exquisite and the actors were marvellous"`
`document = types.Document(content=sentence,type=enums.Document.Type.PLAIN_TEXT,language="en")`
`annotations = client.analyze_sentiment(document=document)`
`print(annotations)`
`document_sentiment {
magnitude: 1.899999976158142
score: 0.8999999761581421
}
language: "en"
sentences {
text {
content: "what a wonderful movie."
begin_offset: -1
}
sentiment {
magnitude: 0.8999999761581421
score: 0.8999999761581421
}
}
sentences {
text {
content: "everything was exquisite and the actors were marvellous"
begin_offset: -1
}
sentiment {
magnitude: 0.8999999761581421
score: 0.8999999761581421
}
}`

**Comment by busunkim96** [comment] 2021-02-19 16:22
I am able to reproduce this:

```py
from google.cloud import language

client = language.LanguageServiceClient()

nl_document = language.Document(
    content="wat een geweldige film. alles was voortreffelijk en de acteurs waren geweldig.",
    type_=language.Document.Type.PLAIN_TEXT,
    language="nl"
)

sentiment = client.analyze_sentiment(document=nl_document)
print(sentiment)
```

```
(env) busunkim@busunkim:~/bugs/python-language-23$ python3 detect_sentiment.py 
document_sentiment {
}
language: "nl"
```

I opened https://issuetracker.google.com/issues/180714982 since this is likely something that needs to be fixed on the backend. Please watch that issue for updates.

**Comment by telpirion** [comment] 2021-03-02 18:54
Since an issue has been opened on the public issue tracker, I'm closing this issue on the client library.

**Closed by telpirion** 2021-03-02 18:54 UTC
Labels: api: language, external, priority: p2, type: bug

**Comment by chees** [comment] 2022-03-14 15:03
FYI: this is fixed.
